context:
  version: "0.2.0rc1"

package:
  name: jupyterlab-commands-toolkit
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterlab-commands-toolkit/jupyterlab_commands_toolkit-${{ version }}.tar.gz
  sha256: b16ccb5b8462d1398341c0a3750e557817cb82ae9b9ec6ea945e84adc1b55cd0

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder >=0.5
  run:
    - python >=${{ python_min }}
    - jupyter_server >=2.4.0,<3

tests:
  - python:
      imports:
        - jupyterlab_commands_toolkit
      pip_check: true
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/jupyter-ai-contrib/jupyterlab-commands-toolkit
  summary: "JupyterLab commands as an AI Toolkit"
  license: BSD-3-Clause
  license_file: LICENSE
  documentation: https://jupyter-ai.readthedocs.io/
  repository: https://github.com/jupyter-ai-contrib/jupyterlab-commands-toolkit

extra:
  recipe-maintainers:
    - jtpio
    - dlqqq
    - andrii-i
