context:
  version: "0.2.0"

package:
  name: jupyterlab-commands-toolkit
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterlab-commands-toolkit/jupyterlab_commands_toolkit-${{ version }}.tar.gz
  sha256: fe41978c4c7342e24b63fad2bf21de023eb9afb895c91b3e93a2354b9b83790f

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder >=0.5
  run:
    - python >=${{ python_min }}
    - jupyter_server >=2.4.0,<3

tests:
  - python:
      imports:
        - jupyterlab_commands_toolkit
      pip_check: true
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/jupyter-ai-contrib/jupyterlab-commands-toolkit
  summary: "JupyterLab commands as an AI Toolkit"
  license: BSD-3-Clause
  license_file: LICENSE
  documentation: https://jupyter-ai.readthedocs.io/
  repository: https://github.com/jupyter-ai-contrib/jupyterlab-commands-toolkit

extra:
  recipe-maintainers:
    - jtpio
    - dlqqq
    - andrii-i
